name: Send Bluesky Post

on:
  push:  # Der Workflow wird bei jedem Push ausgeführt
    branches:
      - main  # Nur auf dem "main"-Branch

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Post to Bluesky
        uses: myConsciousness/bluesky-post@v5
        with:
          text: "Autopost via Github actions: Updated my GENious Repo
    for GEN routines in Csound. https://github.com/PvonN/GENious"
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
	  retry-count: 5